[project]
name = "px4-autopilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "empty>=0.4.4",
    "empy==3.3.4",
    "future>=1.0.0",
    "jinja2>=3.1.6",
    "jsonschema>=4.24.0",
    "kconfiglib>=14.1.0",
    "numpy>=2.2.6",
    "packaging>=25.0",
    "pandas>=2.3.0",
    "pyros-genmsg>=0.5.8",
    "pyserial>=3.5",
    "pyyaml>=6.0.2",
    "toml>=0.10.2",
]
